/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc1822Sol from "./draft-IERC1822.sol";
export type { draftIerc1822Sol };
import type * as draftIerc2612Sol from "./draft-IERC2612.sol";
export type { draftIerc2612Sol };
export type { IERC1271 } from "./IERC1271";
export type { IERC1363 } from "./IERC1363";
export type { IERC1363Receiver } from "./IERC1363Receiver";
export type { IERC1363Spender } from "./IERC1363Spender";
export type { IERC2981 } from "./IERC2981";
export type { IERC3156FlashBorrower } from "./IERC3156FlashBorrower";
export type { IERC3156FlashLender } from "./IERC3156FlashLender";
export type { IERC4626 } from "./IERC4626";
