/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftErc20PermitSol from "./draft-ERC20Permit.sol";
export type { draftErc20PermitSol };
import type * as draftIerc20PermitSol from "./draft-IERC20Permit.sol";
export type { draftIerc20PermitSol };
export type { ERC20Burnable } from "./ERC20Burnable";
export type { ERC20Capped } from "./ERC20Capped";
export type { ERC20FlashMint } from "./ERC20FlashMint";
export type { ERC20Pausable } from "./ERC20Pausable";
export type { ERC20Snapshot } from "./ERC20Snapshot";
export type { ERC20Votes } from "./ERC20Votes";
export type { ERC20VotesComp } from "./ERC20VotesComp";
export type { ERC20Wrapper } from "./ERC20Wrapper";
export type { ERC4626 } from "./ERC4626";
export type { IERC20Metadata } from "./IERC20Metadata";
