/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../../../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AuthorizedOperator = ContractEventLog<{
  operator: string;
  tokenHolder: string;
  0: string;
  1: string;
}>;
export type Burned = ContractEventLog<{
  operator: string;
  from: string;
  amount: string;
  data: string;
  operatorData: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type Minted = ContractEventLog<{
  operator: string;
  to: string;
  amount: string;
  data: string;
  operatorData: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type RevokedOperator = ContractEventLog<{
  operator: string;
  tokenHolder: string;
  0: string;
  1: string;
}>;
export type Sent = ContractEventLog<{
  operator: string;
  from: string;
  to: string;
  amount: string;
  data: string;
  operatorData: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
}>;

export interface IERC777 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IERC777;
  clone(): IERC777;
  methods: {
    authorizeOperator(operator: string): NonPayableTransactionObject<void>;

    balanceOf(owner: string): NonPayableTransactionObject<string>;

    burn(
      amount: number | string | BN,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    defaultOperators(): NonPayableTransactionObject<string[]>;

    granularity(): NonPayableTransactionObject<string>;

    isOperatorFor(
      operator: string,
      tokenHolder: string
    ): NonPayableTransactionObject<boolean>;

    name(): NonPayableTransactionObject<string>;

    operatorBurn(
      account: string,
      amount: number | string | BN,
      data: string | number[],
      operatorData: string | number[]
    ): NonPayableTransactionObject<void>;

    operatorSend(
      sender: string,
      recipient: string,
      amount: number | string | BN,
      data: string | number[],
      operatorData: string | number[]
    ): NonPayableTransactionObject<void>;

    revokeOperator(operator: string): NonPayableTransactionObject<void>;

    send(
      recipient: string,
      amount: number | string | BN,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    symbol(): NonPayableTransactionObject<string>;

    totalSupply(): NonPayableTransactionObject<string>;
  };
  events: {
    AuthorizedOperator(cb?: Callback<AuthorizedOperator>): EventEmitter;
    AuthorizedOperator(
      options?: EventOptions,
      cb?: Callback<AuthorizedOperator>
    ): EventEmitter;

    Burned(cb?: Callback<Burned>): EventEmitter;
    Burned(options?: EventOptions, cb?: Callback<Burned>): EventEmitter;

    Minted(cb?: Callback<Minted>): EventEmitter;
    Minted(options?: EventOptions, cb?: Callback<Minted>): EventEmitter;

    RevokedOperator(cb?: Callback<RevokedOperator>): EventEmitter;
    RevokedOperator(
      options?: EventOptions,
      cb?: Callback<RevokedOperator>
    ): EventEmitter;

    Sent(cb?: Callback<Sent>): EventEmitter;
    Sent(options?: EventOptions, cb?: Callback<Sent>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "AuthorizedOperator", cb: Callback<AuthorizedOperator>): void;
  once(
    event: "AuthorizedOperator",
    options: EventOptions,
    cb: Callback<AuthorizedOperator>
  ): void;

  once(event: "Burned", cb: Callback<Burned>): void;
  once(event: "Burned", options: EventOptions, cb: Callback<Burned>): void;

  once(event: "Minted", cb: Callback<Minted>): void;
  once(event: "Minted", options: EventOptions, cb: Callback<Minted>): void;

  once(event: "RevokedOperator", cb: Callback<RevokedOperator>): void;
  once(
    event: "RevokedOperator",
    options: EventOptions,
    cb: Callback<RevokedOperator>
  ): void;

  once(event: "Sent", cb: Callback<Sent>): void;
  once(event: "Sent", options: EventOptions, cb: Callback<Sent>): void;
}
