/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as escrow from "./escrow";
export type { escrow };
import type * as introspection from "./introspection";
export type { introspection };
import type * as structs from "./structs";
export type { structs };
export type { Multicall } from "./Multicall";
