/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface MinimalForwarder extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MinimalForwarder;
  clone(): MinimalForwarder;
  methods: {
    execute(
      req: [
        string,
        string,
        number | string | BN,
        number | string | BN,
        number | string | BN,
        string | number[]
      ],
      signature: string | number[]
    ): PayableTransactionObject<{
      0: boolean;
      1: string;
    }>;

    getNonce(from: string): NonPayableTransactionObject<string>;

    verify(
      req: [
        string,
        string,
        number | string | BN,
        number | string | BN,
        number | string | BN,
        string | number[]
      ],
      signature: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
